version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: atendechat-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: atendechat_password
      POSTGRES_USER: atendechat_user
      POSTGRES_DB: atendechat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U atendechat_user -d atendechat"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: atendechat-redis
    restart: always
    command: redis-server --requirepass redis_password123
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: atendechat-network